Repository pubnub/c-sharp, pull requests merged in 2023-10, with the labels that each got.

#192 Fix malformed `versions.json`
  .github/workflows/release/versions.json
Labels: status: done, priority: high, type: build

#194 Update `CODEOWNERS` list
  .github/CODEOWNERS
Labels: status: done, priority: medium, type: chore

#193 Fix/here_now
  .pubnub.yml
  CHANGELOG
  src/Api/PubnubApi/Builder/UrlRequestBuilder.cs
  src/Api/PubnubApi/Properties/AssemblyInfo.cs
  src/Api/PubnubApi/PubnubApi.csproj
  src/Api/PubnubApiPCL/PubnubApiPCL.csproj
  src/Api/PubnubApiUWP/PubnubApiUWP.csproj
  src/Api/PubnubApiUnity/PubnubApiUnity.csproj
Labels: status: done, priority: medium, type: fix
